app:
  demo-seed:
    enabled: false

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  flyway:
    clean-disabled: true

logging:
  level:
    com.school.erp: INFO
    org.hibernate.SQL: WARN
    root: WARN
