CREATE TABLE leave_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    applicant_role VARCHAR(20) NOT NULL,
    student_id BIGINT,
    teacher_id BIGINT,
    leave_type VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approver_user_id BIGINT,
    approver_remarks VARCHAR(500),
    balance_snapshot_json JSON,
    is_active BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    INDEX idx_leave_tenant_status (tenant_id, status),
    INDEX idx_leave_applicant (tenant_id, applicant_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
