CREATE TABLE IF NOT EXISTS notification_campaign (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id VARCHAR(50) NOT NULL,
  is_active BIT NOT NULL DEFAULT b'1',
  is_deleted BIT NOT NULL DEFAULT b'0',
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(100) NULL,
  updated_by VARCHAR(100) NULL,
  campaign_id VARCHAR(80) NOT NULL,
  title VARCHAR(200) NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  target_audience VARCHAR(20) NOT NULL,
  target_class_id BIGINT NULL,
  target_section_id BIGINT NULL,
  channels_csv VARCHAR(200) NOT NULL,
  locale_code VARCHAR(10) NULL,
  status VARCHAR(20) NOT NULL,
  recipient_count INT NOT NULL DEFAULT 0,
  queued_count INT NOT NULL DEFAULT 0,
  scheduled_at DATETIME NULL,
  UNIQUE KEY uk_nc_tenant_campaign (tenant_id, campaign_id),
  KEY idx_nc_tenant_created (tenant_id, created_at),
  KEY idx_nc_tenant_campaign (tenant_id, campaign_id)
);

CREATE TABLE IF NOT EXISTS notification_campaign_template (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id VARCHAR(50) NOT NULL,
  is_active BIT NOT NULL DEFAULT b'1',
  is_deleted BIT NOT NULL DEFAULT b'0',
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(100) NULL,
  updated_by VARCHAR(100) NULL,
  event_type VARCHAR(80) NOT NULL,
  channel VARCHAR(20) NOT NULL,
  locale_code VARCHAR(10) NOT NULL,
  template_body VARCHAR(2000) NOT NULL,
  dlt_template_id VARCHAR(120) NULL,
  status VARCHAR(20) NOT NULL,
  UNIQUE KEY uk_nct_tenant_event_channel_locale (tenant_id, event_type, channel, locale_code),
  KEY idx_nct_tenant_key (tenant_id, event_type, channel, locale_code),
  KEY idx_nct_tenant_status (tenant_id, status)
);
