-- Phase 1 (fees-v2): domain stabilization with additive canonical tables.
-- MySQL 8 compatible, no breaking changes to existing fee_payments / fee_transactions.

CREATE TABLE fee_component_master (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(120) NOT NULL,
    component_type VARCHAR(20) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    optional_component TINYINT(1) NOT NULL DEFAULT 0,
    refundable TINYINT(1) NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fcm_tenant_year_code (tenant_id, academic_year_id, code),
    KEY idx_fcm_tenant_year_active (tenant_id, academic_year_id, is_deleted, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_structure (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    structure_name VARCHAR(120) NOT NULL,
    version_no INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    rule_expression VARCHAR(1000) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fee_structure_version (tenant_id, academic_year_id, class_id, structure_name, version_no),
    KEY idx_fee_structure_tenant_class (tenant_id, academic_year_id, class_id, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_structure_component (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    fee_structure_id BIGINT NOT NULL,
    fee_component_master_id BIGINT NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    frequency_override VARCHAR(20) NULL,
    optional_override TINYINT(1) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fsc_unique_component (tenant_id, academic_year_id, fee_structure_id, fee_component_master_id),
    KEY idx_fsc_structure (tenant_id, academic_year_id, fee_structure_id, is_deleted),
    CONSTRAINT fk_fsc_structure FOREIGN KEY (fee_structure_id) REFERENCES fee_structure(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE student_fee_structure_map (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    fee_structure_id BIGINT NOT NULL,
    frozen_version_no INT NOT NULL,
    assignment_source VARCHAR(30) NOT NULL,
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    snapshot_json JSON NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_sfsm_student_active (tenant_id, academic_year_id, student_id, is_deleted, is_active),
    KEY idx_sfsm_structure (tenant_id, academic_year_id, fee_structure_id, is_deleted),
    CONSTRAINT fk_sfsm_structure FOREIGN KEY (fee_structure_id) REFERENCES fee_structure(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_demand_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    run_type VARCHAR(20) NOT NULL,
    period_key VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    trigger_source VARCHAR(30) NOT NULL,
    triggered_by_user_id BIGINT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    run_metadata_json JSON NULL,
    started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at DATETIME(6) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fee_demand_run_idempotency (tenant_id, academic_year_id, idempotency_key),
    KEY idx_fee_demand_run_period (tenant_id, academic_year_id, period_key, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_demand (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    fee_component_master_id BIGINT NOT NULL,
    fee_structure_id BIGINT NOT NULL,
    demand_run_id BIGINT NOT NULL,
    period_key VARCHAR(20) NOT NULL,
    due_date DATE NOT NULL,
    principal_amount DECIMAL(14,2) NOT NULL,
    discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    late_fee_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(14,2) NOT NULL,
    outstanding_amount DECIMAL(14,2) NOT NULL,
    demand_status VARCHAR(20) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fee_demand_dedup (tenant_id, academic_year_id, student_id, fee_component_master_id, period_key),
    KEY idx_fee_demand_student_status (tenant_id, academic_year_id, student_id, demand_status, due_date),
    KEY idx_fee_demand_run (tenant_id, academic_year_id, demand_run_id),
    CONSTRAINT fk_fee_demand_run FOREIGN KEY (demand_run_id) REFERENCES fee_demand_run(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    payment_no VARCHAR(80) NOT NULL,
    channel_type VARCHAR(20) NOT NULL,
    payment_mode VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    external_ref_id VARCHAR(120) NULL,
    instrument_ref VARCHAR(120) NULL,
    receipt_no VARCHAR(80) NULL,
    payment_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    idempotency_key VARCHAR(120) NOT NULL,
    payment_metadata_json JSON NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_payment_no (tenant_id, academic_year_id, payment_no),
    UNIQUE KEY uq_payment_idempotency (tenant_id, academic_year_id, idempotency_key),
    KEY idx_payment_student_date (tenant_id, academic_year_id, student_id, payment_date),
    KEY idx_payment_external (tenant_id, external_ref_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_allocation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    fee_demand_id BIGINT NULL,
    allocation_type VARCHAR(20) NOT NULL,
    amount_allocated DECIMAL(14,2) NOT NULL,
    allocation_order INT NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_payment_allocation_payment (tenant_id, academic_year_id, payment_id, allocation_order),
    KEY idx_payment_allocation_demand (tenant_id, academic_year_id, fee_demand_id),
    CONSTRAINT fk_payment_allocation_payment FOREIGN KEY (payment_id) REFERENCES payment(id),
    CONSTRAINT fk_payment_allocation_demand FOREIGN KEY (fee_demand_id) REFERENCES fee_demand(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE student_ledger (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    entry_type VARCHAR(10) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_ref_id BIGINT NULL,
    source_ref_code VARCHAR(80) NULL,
    amount DECIMAL(14,2) NOT NULL,
    signed_amount DECIMAL(14,2) NOT NULL,
    running_balance DECIMAL(14,2) NOT NULL,
    txn_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    narrative VARCHAR(255) NULL,
    metadata_json JSON NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_student_ledger_student_txn (tenant_id, academic_year_id, student_id, txn_time, id),
    KEY idx_student_ledger_source (tenant_id, academic_year_id, source_type, source_ref_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE student_discount (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value DECIMAL(14,2) NOT NULL,
    component_scope VARCHAR(20) NOT NULL DEFAULT 'ALL',
    applicable_component_ids_json JSON NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    reason VARCHAR(255) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_student_discount_student (tenant_id, academic_year_id, student_id, is_deleted, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    rule_code VARCHAR(80) NOT NULL,
    rule_name VARCHAR(160) NOT NULL,
    rule_type VARCHAR(30) NOT NULL,
    priority_no INT NOT NULL DEFAULT 100,
    rule_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    stop_on_match TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    UNIQUE KEY uq_fee_rule_code (tenant_id, academic_year_id, rule_code),
    KEY idx_fee_rule_priority (tenant_id, academic_year_id, rule_status, priority_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_rule_condition (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    fee_rule_id BIGINT NOT NULL,
    condition_order INT NOT NULL,
    field_name VARCHAR(80) NOT NULL,
    operator VARCHAR(30) NOT NULL,
    value_type VARCHAR(20) NOT NULL,
    value_text VARCHAR(255) NULL,
    value_number DECIMAL(14,2) NULL,
    value_json JSON NULL,
    logical_join VARCHAR(10) NOT NULL DEFAULT 'AND',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_fee_rule_condition_rule (tenant_id, academic_year_id, fee_rule_id, condition_order),
    CONSTRAINT fk_fee_rule_condition_rule FOREIGN KEY (fee_rule_id) REFERENCES fee_rule(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fee_rule_action (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    academic_year_id BIGINT NOT NULL,
    fee_rule_id BIGINT NOT NULL,
    action_order INT NOT NULL,
    action_type VARCHAR(40) NOT NULL,
    target_scope VARCHAR(30) NULL,
    value_type VARCHAR(20) NULL,
    value_number DECIMAL(14,2) NULL,
    value_text VARCHAR(255) NULL,
    value_json JSON NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    KEY idx_fee_rule_action_rule (tenant_id, academic_year_id, fee_rule_id, action_order),
    CONSTRAINT fk_fee_rule_action_rule FOREIGN KEY (fee_rule_id) REFERENCES fee_rule(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
