-- Remove seeded demo videos from public listing. Sales uploads (published=true) will appear automatically.
UPDATE marketing_videos
SET published = b'0', featured = b'0'
WHERE slug IN ('eduportal-overview', 'fees-and-collections')
   OR youtube_url LIKE '%dQw4w9WgXcQ%'
   OR youtube_url LIKE '%FTQbiNvZqaY%';

-- Expand public feature catalog to reflect core Edu Portal SaaS modules.
-- Upsert by slug so existing environments can refresh names/descriptions safely.
INSERT INTO marketing_feature_modules (
  id, slug, name, category, short_description, detailed_description, highlights, enabled_for_marketing, sort_order, status
) VALUES
  (UUID(), 'dashboard', 'Unified Dashboard', 'Dashboard',
   'A single command center for academic, financial, and operational health.',
   'Role-based dashboards for owners, principals, and operations teams with drill-down visibility.',
   'Role-based widgets|KPI trends|Executive drill-down', b'1', 10, 'LIVE'),
  (UUID(), 'academic', 'Academic Management', 'Academic',
   'Curriculum, class planning, subjects, and academic-year workflows.',
   'Centralized academic operations with term setup, class allocation, and syllabus progression tracking.',
   'Curriculum mapping|Teacher allocation|Academic calendar', b'1', 20, 'LIVE'),
  (UUID(), 'attendance', 'Attendance Management', 'Academic',
   'Daily attendance with class-level, teacher-level, and parent visibility.',
   'Fast attendance capture with exception handling, late trends, and alert workflows.',
   'Daily attendance|Late alerts|Absence insights', b'1', 30, 'LIVE'),
  (UUID(), 'exams', 'Exam & Result Engine', 'Academic',
   'Config-driven exams, marks processing, and report card generation.',
   'Supports board-aware structures, grading schemas, and scalable result publishing.',
   'Exam workflows|Marks entry|Report cards', b'1', 40, 'LIVE'),
  (UUID(), 'fees', 'Fees & Collections', 'Finance',
   'Structures, invoices, reminders, reconciliation, and receipts.',
   'End-to-end fee lifecycle with audit trail and finance office controls.',
   'Payment reminders|Online payments|Reconciliation', b'1', 50, 'LIVE'),
  (UUID(), 'payroll', 'Payroll & Staff Payouts', 'Finance',
   'Salary structures, payroll runs, and controlled disbursement workflow.',
   'School payroll operations with configurable allowances, deductions, and approval checkpoints.',
   'Salary components|Payroll runs|Payout logs', b'1', 60, 'LIVE'),
  (UUID(), 'communication', 'Communication & Inbox', 'Communication',
   'Targeted communication for school, teacher, student, and parent stakeholders.',
   'Broadcasts, direct role-based messaging, and delivery status tracking.',
   'Targeted broadcasts|Role inbox|Delivery tracking', b'1', 70, 'LIVE'),
  (UUID(), 'transport', 'Transport Operations', 'Operations',
   'Route planning, stoppage mapping, and transport monitoring.',
   'Transport desk workflows for route assignments, ridership updates, and alerts.',
   'Route planning|Stop assignments|Transport visibility', b'1', 80, 'LIVE'),
  (UUID(), 'library', 'Library Management', 'Operations',
   'Catalog, circulation, membership, and due-date management.',
   'Library operations with issue-return tracking and policy enforcement.',
   'Catalog management|Issue-return|Due tracking', b'1', 90, 'LIVE'),
  (UUID(), 'hostel', 'Hostel Management', 'Operations',
   'Hostel allocation, billing touchpoints, and incident workflow.',
   'Multi-role hostel operations with occupancy, approvals, and parent/student visibility.',
   'Room allocation|Hostel billing|Incident register', b'1', 100, 'LIVE'),
  (UUID(), 'documents', 'Document Center', 'Operations',
   'Institution document workflows for records, proofs, and controlled access.',
   'Organized document lifecycle with role-safe visibility and compliance-ready structure.',
   'Central repository|Role-safe access|Record lifecycle', b'1', 110, 'LIVE'),
  (UUID(), 'reports', 'Reports & Analytics', 'Insights',
   'Operational, academic, and financial reporting for leadership decisions.',
   'Consolidated dashboards and exports for management, audit, and compliance reviews.',
   'Executive reports|Operational analytics|Export center', b'1', 120, 'LIVE'),
  (UUID(), 'operations-hub', 'Operations Hub', 'Operations',
   'Cross-functional school operations orchestration from one place.',
   'Central command surface for recurring tasks, escalations, and operational SLAs.',
   'Task orchestration|Escalation tracking|SLA visibility', b'1', 130, 'LIVE'),
  (UUID(), 'import-export', 'Import & Export', 'Platform',
   'Bulk data onboarding and controlled exports for school teams.',
   'High-volume import/export workflows with validation and operational safeguards.',
   'Bulk onboarding|Validation checks|Controlled exports', b'1', 140, 'LIVE'),
  (UUID(), 'directory', 'School Directory', 'Platform',
   'Unified directory for students, teachers, and staff records.',
   'Searchable and role-filtered directory designed for daily school operations.',
   'Unified directory|Role filtering|Quick search', b'1', 150, 'LIVE'),
  (UUID(), 'settings', 'School Settings', 'Platform',
   'Tenant-safe settings for branding, academic structure, and operational preferences.',
   'Centralized school configuration aligned with multi-tenant and academic-year partitioning.',
   'Tenant-safe controls|Academic year setup|Policy settings', b'1', 160, 'LIVE'),
  (UUID(), 'parent-portal', 'Parent & Student Portal', 'Experience',
   'Portal experience for attendance, progress, communication, and fee status.',
   'Role-focused portal surfaces for engagement, transparency, and trust.',
   'Portal visibility|Parent engagement|Student updates', b'1', 170, 'LIVE'),
  (UUID(), 'audit', 'Audit & Compliance', 'Security',
   'Audit trails and compliance-ready traceability for critical operations.',
   'Reviewable history for privileged actions and key workflow transitions.',
   'Audit trail|Compliance visibility|Action traceability', b'1', 180, 'LIVE')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  short_description = VALUES(short_description),
  detailed_description = VALUES(detailed_description),
  highlights = VALUES(highlights),
  enabled_for_marketing = VALUES(enabled_for_marketing),
  sort_order = VALUES(sort_order),
  status = VALUES(status);
