apiVersion: v1
kind: Secret
metadata:
  name: edu-portal-backend-secret
  namespace: edu-portal
type: Opaque
stringData:
  DEV_DB_URL: "jdbc:mysql://<host>:3306/school_erp?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  DEV_DB_USERNAME: "<db_user>"
  DEV_DB_PASSWORD: "<db_password>"
  REDIS_HOST: "<redis_host>"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "<redis_user>"
  REDIS_PASSWORD: "<redis_password>"
  JWT_SECRET: "<very_long_random_secret>"
  APP_INTERNAL_JOB_KEY: "<internal_jobs_key>"
  SENDGRID_API_KEY: "<sendgrid_key_optional>"
  BREVO_API_KEY: "<brevo_key_optional>"
  AWS_SES_ACCESS_KEY: "<aws_ses_access_key_optional>"
  AWS_SES_SECRET_KEY: "<aws_ses_secret_key_optional>"

